# Generated by Django 3.0.2 on 2020-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4', '0002_auto_20200124_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
