# Generated by Django 3.0.2 on 2020-01-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c4', '0003_auto_20200124_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['pk'], 'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='end',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='start',
            new_name='start_datetime',
        ),
    ]
