# Generated by Django 3.0.2 on 2020-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c4', '0004_auto_20200126_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
